'use client';

import { useEffect, useState } from 'react';
import { useToast } from '../Toast';
import { getReport } from '@/lib/report';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export default function LaporanPage() {
  const { showToast } = useToast();

  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
  }, []);

  async function fetchReport() {
    try {
      setLoading(true);

      const token = localStorage.getItem('accessToken');
      if (!token) return;

      const res = await getReport(token);
      setReport(res.data);
    } catch (err) {
      console.error(err);
      showToast('Error', 'Gagal mengambil laporan');
    } finally {
      setLoading(false);
    }
  }

  function formatRupiah(val: number) {
    return `Rp ${Number(val).toLocaleString('id-ID')}`;
  }

  // EXPORT PDF
  function exportPDF() {
    if (!report) return;

    const doc = new jsPDF();

    const { summary, categories, month } = report;

    // HEADER
    doc.setFillColor(99, 102, 241);
    doc.rect(0, 0, 220, 30, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text('FINANCE REPORT', 14, 12);

    doc.setFontSize(10);
    doc.text(`Periode: ${month}`, 14, 22);

    // SUMMARY BOX
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    doc.text('Ringkasan Keuangan', 14, 45);

    const summaryData = [
      ['Total Pemasukan', `Rp ${summary.totalIncome.toLocaleString('id-ID')}`],
      [
        'Total Pengeluaran',
        `Rp ${summary.totalExpense.toLocaleString('id-ID')}`,
      ],
      ['Tabungan Bersih', `Rp ${summary.netSavings.toLocaleString('id-ID')}`],
      ['Rasio Tabungan', `${summary.savingsRatio}%`],
    ];

    autoTable(doc, {
      startY: 50,
      head: [['Item', 'Nilai']],
      body: summaryData,
      theme: 'grid',
      styles: {
        fontSize: 10,
        cellPadding: 4,
      },
      headStyles: {
        fillColor: [99, 102, 241],
        textColor: 255,
      },
    });

    // CATEGORY TABLE
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Kategori', 'Total Pengeluaran']],
      body: categories.map((c: any) => [
        c.categoryName,
        `Rp ${c.totalAmount.toLocaleString('id-ID')}`,
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: 255,
      },
    });

    // FOOTER
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      'Generated by Finance App • Confidential Report',
      14,
      pageHeight - 10,
    );

    // SAVE FILE
    doc.save(`finance-report-${month}.pdf`);
  }

  // EXPORT EXCEL
  function exportExcel() {
    if (!report) return;

    const { summary, categories, month } = report;

    // SHEET 1: SUMMARY
    const summarySheet = [
      ['FINANCE REPORT'],
      [`Periode: ${month}`],
      [],
      ['Total Pemasukan', summary.totalIncome],
      ['Total Pengeluaran', summary.totalExpense],
      ['Tabungan Bersih', summary.netSavings],
      ['Rasio Tabungan (%)', summary.savingsRatio],
    ];

    const wsSummary = XLSX.utils.aoa_to_sheet(summarySheet);

    // SHEET 2: DETAIL KATEGORI
    const detailSheet = [
      ['Kategori', 'Total Pengeluaran'],
      ...categories.map((c: any) => [c.categoryName, c.totalAmount]),
    ];

    const wsDetail = XLSX.utils.aoa_to_sheet(detailSheet);

    // SHEET 3: TREND (dummy / API optional)
    const trendSheet = [
      ['Kategori', 'Bulan', 'Total'],
      ...categories.map((c: any) => [c.categoryName, month, c.totalAmount]),
    ];

    const wsTrend = XLSX.utils.aoa_to_sheet(trendSheet);

    // WORKBOOK
    const wb = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
    XLSX.utils.book_append_sheet(wb, wsDetail, 'Detail');
    XLSX.utils.book_append_sheet(wb, wsTrend, 'Trend');

    // DOWNLOAD
    XLSX.writeFile(wb, `finance-report-${month}.xlsx`);
  }

  if (loading) {
    return <div style={{ padding: 20 }}>Loading...</div>;
  }

  if (!report) {
    return <div style={{ padding: 20 }}>Tidak ada data</div>;
  }

  const { summary, categories, month } = report;

  return (
    <div>
      {/* ================= EXPORT BUTTON ================= */}
      <div className="export-btns">
        <button className="export-btn" onClick={exportPDF}>
          Export PDF
        </button>

        <button className="export-btn" onClick={exportExcel}>
          Export Excel
        </button>

        <button
          className="export-btn"
          onClick={() => showToast('Bagikan', 'Link laporan disalin!')}
        >
          Bagikan
        </button>
      </div>

      {/* ================= SUMMARY ================= */}
      <div className="report-card">
        <div
          style={{
            fontFamily: "'Syne',sans-serif",
            fontSize: '14px',
            fontWeight: 600,
            marginBottom: '12px',
          }}
        >
          Ringkasan {month}
        </div>

        <div className="report-row">
          <span>Total Pemasukan</span>
          <span style={{ color: 'var(--green)' }}>
            {formatRupiah(summary.totalIncome)}
          </span>
        </div>

        <div className="report-row">
          <span>Total Pengeluaran</span>
          <span style={{ color: 'var(--red)' }}>
            {formatRupiah(summary.totalExpense)}
          </span>
        </div>

        <div className="report-row">
          <span>Tabungan Bersih</span>
          <span style={{ color: 'var(--purple2)' }}>
            {formatRupiah(summary.netSavings)}
          </span>
        </div>

        <div className="report-row">
          <span>Rasio Tabungan</span>
          <span style={{ color: 'var(--green)' }}>{summary.savingsRatio}%</span>
        </div>
      </div>

      {/* ================= CATEGORY ================= */}
      <div className="report-card">
        <div
          style={{
            fontFamily: "'Syne',sans-serif",
            fontSize: '14px',
            fontWeight: 600,
            marginBottom: '12px',
          }}
        >
          Detail per Kategori
        </div>

        {categories.map((c: any) => (
          <div key={c.categoryName} className="report-row">
            <span>{c.categoryName}</span>
            <span>{formatRupiah(c.totalAmount)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
